/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fcf8fa",
        "outline-variant": "#c6c6cd",
        "secondary": "#5c5f61",
        "background": "#fcf8fa",
        "secondary-fixed": "#e0e3e5",
        "surface-container": "#f0edef",
        "inverse-primary": "#bec6e0",
        "on-secondary-fixed": "#191c1e",
        "inverse-surface": "#303032",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-container": "#7c839b",
        "on-secondary-container": "#626567",
        "outline": "#76777d",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2e4",
        "tertiary-fixed-dim": "#4edea3",
        "on-background": "#1b1b1d",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-container": "#002113",
        "primary-container": "#131b2e",
        "on-error": "#ffffff",
        "surface": "#fcf8fa",
        "surface-container-high": "#eae7e9",
        "on-secondary-fixed-variant": "#444749",
        "on-tertiary-container": "#009668",
        "tertiary": "#000000",
        "surface-container-low": "#f6f3f5",
        "error": "#ba1a1a",
        "primary": "#000000",
        "surface-dim": "#dcd9db",
        "error-container": "#ffdad6",
        "secondary-container": "#e0e3e5",
        "on-tertiary-fixed": "#002113",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#45464d",
        "on-tertiary": "#ffffff",
        "surface-tint": "#565e74",
        "inverse-on-surface": "#f3f0f2",
        "primary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1b1d",
        "on-primary-fixed": "#131b2e",
        "surface-container-highest": "#e4e2e4",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#c4c7c9",
        apple: {
          bg: '#FBFBFB',
          surface: '#FFFFFF',
          text: '#1D1D1F',
          secondary: '#6E6E73',
          border: '#E5E5E5',
          new: '#323232',
          progress: '#D97706',
          resolved: '#059669',
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "xs": "4px",
        "xl": "40px",
        "lg": "24px",
        "gutter": "24px",
        "unit": "4px",
        "container-max": "1200px",
        "md": "16px",
        "xxl": "64px"
      },
      fontFamily: {
        "h2": ["Public Sans", "sans-serif"],
        "caption": ["Public Sans", "sans-serif"],
        "h1": ["Public Sans", "sans-serif"],
        "display": ["Public Sans", "sans-serif"],
        "label-caps": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "sans": ["Public Sans", "sans-serif"],
        "mono": ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "caption": ["14px", { "lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "500" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
